service: omni-crm

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  deploymentBucket: ${ssm:/omni-dw/${self:provider.stage}/sls/deployment/bucket}
  role: ${ssm:/omni-dw/${self:provider.stage}/lambda/role}  
  vpc:
    securityGroupIds:
      - ${ssm:/omni-dw/${self:provider.stage}/lambda/sgId}
    subnetIds:
      - ${ssm:/omni-dw/${self:provider.stage}/lambda/subnetA}
  stackTags: 
    Application: MicrosoftDynamicsCRM
    CreateBy: BizCloudExperts
    Environment: ${self:provider.stage} 

custom: 
  serverless-layers:
    functions:
      - customers
      - customers-new
      - sales-summary
      - sales-summary-new
      - global-customers
      - global-customers-new    
    dependenciesPath: ./requirements.txt
    
plugins:
  - serverless-layers
  - serverless-pseudo-parameters
  - serverless-step-functions

package:
  individually: true
  exclude:
  - '**/*'
  - serverless.yml

functions:
  customers: ${file(config/functions/customers.yml):function}
  customers-new: ${file(config/functions/customers-new.yml):function}
  sales-summary: ${file(config/functions/sales-summary.yml):function}
  sales-summary-new: ${file(config/functions/sales-summary-new.yml):function}
  global-customers: ${file(config/functions/global-customers.yml):function}
  global-customers-new: ${file(config/functions/global-customers-new.yml):function}

stepFunctions:
  stateMachines:
    sales-summary-state-machine: ${file(config/step-functions/sales-summary-state-machine.yml):stateMachine}
    sales-summary-state-machine-new: ${file(config/step-functions/sales-summary-state-machine-new.yml):stateMachine}
    global-customers-state-machine: ${file(config/step-functions/global-customers-state-machine.yml):stateMachine}
    global-customers-state-machine-new: ${file(config/step-functions/global-customers-state-machine-new.yml):stateMachine}
    customers-state-machine: ${file(config/step-functions/customers-state-machine.yml):stateMachine}
    customers-state-machine-new: ${file(config/step-functions/customers-state-machine-new.yml):stateMachine}