
function:
  handler: src/customers.handler
  name: ${self:service}-customers-${self:provider.stage}
  description: omni crm dynamics Customers - ${self:provider.stage}
  memorySize: 1024 
  timeout: 900
  # events:  
  #   - schedule:
  #       name: omni-crm-dynamics-customers
  #       description: 'schedule cloud watch event at 1AM and 1PM every day for customers dynamics crm'
  #       # rate: cron(0 1-13 * * ? *)
  #       rate: cron(0/10 * ? * * *) 
  package:
    include:
    - src/customers.py
    - src/common.py
    - psycopg2/*
  environment:
    db_username: ${ssm:/omni-dw/${self:provider.stage}/db/user~true}
    db_password: ${ssm:/omni-dw/${self:provider.stage}/db/password~true}
    db_name: ${ssm:/omni-dw/${self:provider.stage}/db/name}
    db_host: ${ssm:/omni-dw/${self:provider.stage}/db/host~true}
    db_port: ${ssm:/omni-dw/${self:provider.stage}/db/port} 
    REGION: ${self:provider.region}
    customer_table_url: ${ssm:/omni-dw/${self:provider.stage}/customerTableURL}
    timestamp_parameter: /omni-dw/${self:provider.stage}/customers/timestamp
    s3_bucket: ${ssm:/${self:service}/${self:provider.stage}/bucket}
    s3_key: ${ssm:/${self:service}/${self:provider.stage}/customers/s3/key}

