
function:
  handler: src/global-customers_new.handler
  name: ${self:service}-global-customers-new-${self:provider.stage}
  description: omni crm dynamics global customers new - ${self:provider.stage}
  memorySize: 1024 
  timeout: 900
  package:
    include:
    - src/global-customers_new.py
    - src/common.py
    - psycopg2/*
  environment:
    db_username: ${ssm:/omni-dw/${self:provider.stage}/db/user~true}
    db_password: ${ssm:/omni-dw/${self:provider.stage}/db/password~true}
    db_name: ${ssm:/omni-dw/${self:provider.stage}/db/name}
    db_host: ${ssm:/omni-dw/${self:provider.stage}/db/host~true}
    db_port: ${ssm:/omni-dw/${self:provider.stage}/db/port} 
    REGION: ${self:provider.region}
    globalcustomer_table_url_new: ${ssm:/${self:service}/${self:provider.stage}/globalCustomers/url/new}
    timestamp_parameter_new: /${self:service}/${self:provider.stage}/globalCustomers/timestamp/new
    s3_bucket_new: ${ssm:/${self:service}/${self:provider.stage}/bucket/new}
    s3_key: ${ssm:/${self:service}/${self:provider.stage}/globalCustomers/s3/key}
    sns_arn: ${ssm:/${self:service}/${self:provider.stage}/global-customers-new/sns/arn}
