
function:
  handler: src/global-customers.handler
  name: ${self:service}-global-customers-${self:provider.stage}
  description: omni crm dynamics global customers - ${self:provider.stage}
  memorySize: 1024 
  timeout: 900
  tags: 
    Name : global-customers 
  package:
    include:
    - src/global-customers.py
    - src/common.py
    - psycopg2/*
  environment:
    db_username: ${ssm:/omni-dw/${self:provider.stage}/db/user~true}
    db_password: ${ssm:/omni-dw/${self:provider.stage}/db/password~true}
    db_name: ${ssm:/omni-dw/${self:provider.stage}/db/name}
    db_host: ${ssm:/omni-dw/${self:provider.stage}/db/host~true}
    db_port: ${ssm:/omni-dw/${self:provider.stage}/db/port} 
    REGION: ${self:provider.region}
    globalcustomer_table_url: ${ssm:/${self:service}/${self:provider.stage}/globalCustomers/url}
    timestamp_parameter: /${self:service}/${self:provider.stage}/globalCustomers/timestamp
    s3_bucket: ${ssm:/${self:service}/${self:provider.stage}/bucket}
    s3_key: ${ssm:/${self:service}/${self:provider.stage}/globalCustomers/s3/key}
    sns_arn: ${ssm:/${self:service}/${self:provider.stage}/global-customers/sns/arn}

